### ISSUE TITLE
Minor relative-path comment for Manual install Vieschedpp_AUTO instructions

### ISSUE THREAD

**Issue by varenius** [TUW-VieVS/VieSchedpp#10]
*Describe your issue here*

On the Manual install page, this section exists:
```
# install VieSched++ AUTO (optional - auto scheduling program)
# download VieSched++ AUTO
git clone --recurse-submodules https://github.com/TUW-VieVS/VieSchedpp_AUTO.git 
cd VieSchedpp_AUTO
# create virtual environment (I'm using venv here):
python3 -m venv venv
source venv/bin/activate
pip install -r requirements.txt
# alternative using miniconda:
# wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
# bash Miniconda3-latest-Linux-x86_64.sh # follow the installation instructions
# conda env create -f ./VieSchedpp_AUTO/environment.yml # create new environment for VieSchedpp_AUTO
# conda activate VieSchedpp_AUTO # activate the new environment
# [OPTIONAL] test installation: "$ python VieSchedpp_AUTO/VieSchedpp_AUTO.py -h"
```
The venv way first has "cd VieSchedpp_AUTO" which means one is inside the AUTO-folder. These are very minor points, but:

- The conda install appears to assume we're one level up from the AUTO-folder, so in a different folder than the venv way. Is this intentional, or should both be assumed to be at the same level?
- The last point,` [OPTIONAL] test installation: "$ python VieSchedpp_AUTO/VieSchedpp_AUTO.py -h"` technically applies both the venv and conda ways, I presume. But this also assumes we're one level up from the AUTO-folder, so it won't run without at "cd .." up from the venv folder.

Really minor points, I know, but might as well note since I had a "huh?" moment when I copy pasted the test-line :).

**Comment by Matthias-Schartner** [comment]
Thanks for checking the script - I did change it accordingly
